AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Parameters:
  TABLENAME:
    Type: String
    Description: The DynamoDB table for greeting information.
    Default: 'SAMDemoGreeting'
  APIAUTH:
    Type: String
    Description: API Authorizer (NONE or AWS_IAM)
    Default: NONE
Globals:
  Function:
    Runtime: nodejs16.x
    MemorySize: 128
    Timeout: 30
  Api:
    Cors:
      AllowMethods: "'OPTIONS,POST,GET'"
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'*'"
    EndpointConfiguration: REGIONAL
Resources:
  GreetingApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: 'Prod'
      Auth:
        DefaultAuthorizer: !Ref APIAUTH
  MyGreetingDynamoDBGetFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      CodeUri: MyGreetingDynamoDBGetFunction
      Description: ''
      Policies:
        - AmazonDynamoDBReadOnlyAccess
      Events:
        LambdaMicroservice:
          Type: Api
          Properties:
            Path: /hello/{lang}
            Method: GET
            RestApiId: !Ref GreetingApi
      Environment:
        Variables:
          DDB_TABLE: !Ref TABLENAME
          DYNAMDB_LOCALURL: ''
          DYNAMODB_REGION: ''
  MyGreetingDynamoDBPutFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      CodeUri: MyGreetingDynamoDBPutFunction
      Description: ''
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        LambdaMicroservice:
          Type: Api
          Properties:
            Path: /hello/{lang}
            Method: PUT
            RestApiId: !Ref GreetingApi
      Environment:
        Variables:
          DDB_TABLE: !Ref TABLENAME
          DYNAMDB_LOCALURL: ''
          DYNAMODB_REGION: ''
  SAMDemoGreeting:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Ref TABLENAME
      AttributeDefinitions:
        - AttributeName: lang
          AttributeType: S
      KeySchema:
        - AttributeName: lang
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
Outputs:
  GreetingApiUri:
    Value: !Sub "https://${GreetingApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
